# https://docs.travis-ci.com/user/job-lifecycle
sudo: false
language: node_js
node_js:
  - '12'
services:
  - docker
git:
  depth: false
branches:
  only:
    - gh-pages
    - /.*/
cache: npm
install:
  - npm install
after_script:
  - npm run coveralls
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bierteam/pils:$TRAVIS_BRANCH .
  - docker push bierteam/pils
