# https://docs.travis-ci.com/user/job-lifecycle
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
language: node_js
node_js:
  - "12"
env:
  - PART=pils-api
  - PART=bier-import
  - PART=frontend
services:
  - docker
branches:
  only:
    - /.*/ # build all branches
script: cd $PART; npm ci; npm run test
after_script: cd $PART; npm run coverage
deploy:
  provider: script
  on:
    all_branches: true
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker build -t bierteam/$PART:$TRAVIS_BRANCH .; docker push bierteam/$PART:$TRAVIS_BRANCH
