sudo: false
language: node_js
node_js:
- '11'
git:
  depth: false
branches:
  only:
  - master
  - dev
  - vue
cache: npm
install:
- npm ci
before_deploy:
- openssl aes-256-cbc -K $encrypted_0394b0a27270_key -iv $encrypted_0394b0a27270_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
- mv config/backend.example.js config/backend.js
- npm run build
deploy:
  - provider: script
    script: ssh -o StrictHostKeyChecking=no -p$DEV_PORT root@$DEV_SERVER 'cd Pils/; git stash; git checkout dev; git pull; npm ci --only=production; npm i -g pm2; pm2 update; npm restart;'
    on:
      branch: dev
  - provider: script
    script: ssh -o StrictHostKeyChecking=no -p$PRODUCTION_PORT root@$PRODUCTION_SERVER 'cd Pils/; git stash; git checkout master; git pull; npm ci --only=production; npm i -g pm2; pm2 update; npm restart;'
    on:
      branch: master
  - provider: script
    script: ssh -o StrictHostKeyChecking=no -p$DEV_PORT root@$DEV_SERVER 'cd Pils-test/; git stash; git checkout vue; git pull; npm ci --only=production; npm i -g pm2; pm2 update; npm restart;' && rsync -rv -e "ssh -p $DEV_PORT" public/ root@$DEV_SERVER:~/Pils-test/public
    on:
      branch: vue
