# https://docs.travis-ci.com/user/job-lifecycle
sudo: false
language: node_js
node_js:
  - '11'
git:
  depth: false
branches:
  only:
    - gh-pages
    - /.*/
cache: npm
install:
  - npm install
after_script:
  - npm run coveralls
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0394b0a27270_key -iv $encrypted_0394b0a27270_iv
    -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - cp config/backend.example.js config/backend.js
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -o StrictHostKeyChecking=no -p$DEV_PORT root@$DEV_SERVER 'cd Pils/; git stash; git checkout dev; git pull; npm ci --only=production; npm i -g pm2; pm2 update; npm restart;' && rsync -rvz --delete -e "ssh -p $DEV_PORT" public/ root@$DEV_SERVER:~/Pils/public
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: ssh -o StrictHostKeyChecking=no -p$PRODUCTION_PORT root@$PRODUCTION_SERVER 'cd Pils/; git stash; git checkout master; git pull; npm ci --only=production; npm i -g pm2; pm2 update; npm restart;' && rsync -rvz --delete -e "ssh -p $PRODUCTION_PORT" public/ root@$PRODUCTION_SERVER:~/Pils/public
    on:
      branch: master
addons:
  sonarcloud:
    organization: "bierteam"
    token:
      secure: "bQg+Hnpy2ZWJKGsxL+9OSlUJlBAbt19n96H5TmXqmhGQeHfhTStzYQfqJHPjF8q3vQauOZMvo1a78Rtt6AfR9GWCDwlYGw0NjkvMB/mvnZmiB8ArzpHvKJp4MvpX6GiNIaX9IxS30aqkqiMsz5V13ITa2fbfbEgFy+ze4gWXbgnSxaFXxvvJIQpo/s3HiJHpBA+eVWpKfNIqMFIM7lhXkUbaqSR0p/ScqHr2VrCBSIvMiCSnOvl+oZFNe6OEOwa0QETBWdthIWvzDrJRoj7sFBpKwZcRCzT3rew+zZNdRCZWRDqEgwr5rMWsrRTq4ZhEfCl6P2FCNvu5ZoVZTiK+pMhqs93wHf3su96fOw8Yka5gLDEEcQC/2pQe80lnOlezd9O8/+EYpf41b3EDscwW7891zg3t2SzMENGGfxxm3ifWZUMZqXwPWXXsZ/9rraHJdyI1r0gqHAsdkfEZU5n9/6M0Ar5EoY2s2AHrEE1aRloSTfHUWhiLL+K7NKHIV66GtCHluMCgLx4ent9Wv/jW/oZTrCKES2eRIXiiv7d6nQitodTDe5x6enE32TantAfqB7SqEdzeK0nWH3OA4N2Qb7CEzCsl8Q3aRaCxH9yzXIejltMwMXsHcNDNihI0Mv5LBiuKZHcos7GOd5wOliSZyrtw+ldIW6/peZLf1ot5ysQ="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
