sudo: false
language: node_js
node_js:
- '11'
git:
  depth: false
branches:
  only:
  - master
  - dev
cache: npm
install:
- npm ci
before_deploy:
- openssl aes-256-cbc -K $encrypted_7daccfebfa6e_key -iv $encrypted_7daccfebfa6e_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
