# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: drinkn-supermarket-api
#   name: drinkn-supermarket-api
#   namespace: oscar
# spec:
#   replicas: 3
#   revisionHistoryLimit: 10
#   selector:
#     matchLabels:
#       app: drinkn-supermarket-api
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: drinkn-supermarket-api
#     spec:
#       containers:
#       - image: bierteam/supermarket-api:master
#         envFrom:
#         - secretRef:
#             name: drinkn-env
#             optional: false
#         imagePullPolicy: Always
#         name: drinkn-supermarket-api
#         resources: {}
#         securityContext:
#           allowPrivilegeEscalation: false
#           capabilities: {}
#           privileged: false
#           readOnlyRootFilesystem: false
#           runAsNonRoot: false
#         stdin: true
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#         tty: true
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       securityContext: {}
#       terminationGracePeriodSeconds: 30
# status:
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: drinkn-supermarket-api
#   namespace: oscar
# spec:
#   selector:
#     app: drinkn-supermarket-api
#   ports:
#     - port: 80
#       name: default
#       protocol: TCP
#       targetPort: 3000